/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EncyclopediaRouteImport } from './routes/encyclopedia'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HeritageSitesRouteImport } from './routes/heritage-sites'
import { Route as MuseumsRouteImport } from './routes/museums'
import { Route as ApiConciergeRouteImport } from './routes/api/concierge'
import { Route as GovernoratesIdRouteImport } from './routes/governorates.$id'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as LegalConsentRouteImport } from './routes/legal.consent'
import { Route as LegalReviewChecklistRouteImport } from './routes/legal.review-checklist'
import { Route as MarketplaceEgyptianCottonRouteImport } from './routes/marketplace.egyptian-cotton'
import { Route as MarketplaceHandmadeCraftsRouteImport } from './routes/marketplace.handmade-crafts'
import { Route as MarketplaceLocalProducersRouteImport } from './routes/marketplace.local-producers'
import { Route as MarketplaceWearEgyptRouteImport } from './routes/marketplace.wear-egypt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaRoute = EncyclopediaRouteImport.update({
  id: '/encyclopedia',
  path: '/encyclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageSitesRoute = HeritageSitesRouteImport.update({
  id: '/heritage-sites',
  path: '/heritage-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumsRoute = MuseumsRouteImport.update({
  id: '/museums',
  path: '/museums',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConciergeRoute = ApiConciergeRouteImport.update({
  id: '/api/concierge',
  path: '/api/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernoratesIdRoute = GovernoratesIdRouteImport.update({
  id: '/governorates/$id',
  path: '/governorates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConsentRoute = LegalConsentRouteImport.update({
  id: '/legal/consent',
  path: '/legal/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReviewChecklistRoute = LegalReviewChecklistRouteImport.update({
  id: '/legal/review-checklist',
  path: '/legal/review-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceEgyptianCottonRoute =
  MarketplaceEgyptianCottonRouteImport.update({
    id: '/marketplace/egyptian-cotton',
    path: '/marketplace/egyptian-cotton',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceHandmadeCraftsRoute =
  MarketplaceHandmadeCraftsRouteImport.update({
    id: '/marketplace/handmade-crafts',
    path: '/marketplace/handmade-crafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceLocalProducersRoute =
  MarketplaceLocalProducersRouteImport.update({
    id: '/marketplace/local-producers',
    path: '/marketplace/local-producers',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceWearEgyptRoute = MarketplaceWearEgyptRouteImport.update({
  id: '/marketplace/wear-egypt',
  path: '/marketplace/wear-egypt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/events': typeof EventsRoute
  '/heritage-sites': typeof HeritageSitesRoute
  '/museums': typeof MuseumsRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/governorates/$id': typeof GovernoratesIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/review-checklist': typeof LegalReviewChecklistRoute
  '/marketplace/egyptian-cotton': typeof MarketplaceEgyptianCottonRoute
  '/marketplace/handmade-crafts': typeof MarketplaceHandmadeCraftsRoute
  '/marketplace/local-producers': typeof MarketplaceLocalProducersRoute
  '/marketplace/wear-egypt': typeof MarketplaceWearEgyptRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/events': typeof EventsRoute
  '/heritage-sites': typeof HeritageSitesRoute
  '/museums': typeof MuseumsRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/governorates/$id': typeof GovernoratesIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/review-checklist': typeof LegalReviewChecklistRoute
  '/marketplace/egyptian-cotton': typeof MarketplaceEgyptianCottonRoute
  '/marketplace/handmade-crafts': typeof MarketplaceHandmadeCraftsRoute
  '/marketplace/local-producers': typeof MarketplaceLocalProducersRoute
  '/marketplace/wear-egypt': typeof MarketplaceWearEgyptRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/events': typeof EventsRoute
  '/heritage-sites': typeof HeritageSitesRoute
  '/museums': typeof MuseumsRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/governorates/$id': typeof GovernoratesIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/review-checklist': typeof LegalReviewChecklistRoute
  '/marketplace/egyptian-cotton': typeof MarketplaceEgyptianCottonRoute
  '/marketplace/handmade-crafts': typeof MarketplaceHandmadeCraftsRoute
  '/marketplace/local-producers': typeof MarketplaceLocalProducersRoute
  '/marketplace/wear-egypt': typeof MarketplaceWearEgyptRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/contact'
    | '/encyclopedia'
    | '/events'
    | '/heritage-sites'
    | '/museums'
    | '/api/concierge'
    | '/governorates/$id'
    | '/legal/$slug'
    | '/legal/consent'
    | '/legal/review-checklist'
    | '/marketplace/egyptian-cotton'
    | '/marketplace/handmade-crafts'
    | '/marketplace/local-producers'
    | '/marketplace/wear-egypt'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/contact'
    | '/encyclopedia'
    | '/events'
    | '/heritage-sites'
    | '/museums'
    | '/api/concierge'
    | '/governorates/$id'
    | '/legal/$slug'
    | '/legal/consent'
    | '/legal/review-checklist'
    | '/marketplace/egyptian-cotton'
    | '/marketplace/handmade-crafts'
    | '/marketplace/local-producers'
    | '/marketplace/wear-egypt'
    | '/legal'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/contact'
    | '/encyclopedia'
    | '/events'
    | '/heritage-sites'
    | '/museums'
    | '/api/concierge'
    | '/governorates/$id'
    | '/legal/$slug'
    | '/legal/consent'
    | '/legal/review-checklist'
    | '/marketplace/egyptian-cotton'
    | '/marketplace/handmade-crafts'
    | '/marketplace/local-producers'
    | '/marketplace/wear-egypt'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EncyclopediaRoute: typeof EncyclopediaRoute
  EventsRoute: typeof EventsRoute
  HeritageSitesRoute: typeof HeritageSitesRoute
  MuseumsRoute: typeof MuseumsRoute
  ApiConciergeRoute: typeof ApiConciergeRoute
  GovernoratesIdRoute: typeof GovernoratesIdRoute
  LegalSlugRoute: typeof LegalSlugRoute
  LegalConsentRoute: typeof LegalConsentRoute
  LegalReviewChecklistRoute: typeof LegalReviewChecklistRoute
  MarketplaceEgyptianCottonRoute: typeof MarketplaceEgyptianCottonRoute
  MarketplaceHandmadeCraftsRoute: typeof MarketplaceHandmadeCraftsRoute
  MarketplaceLocalProducersRoute: typeof MarketplaceLocalProducersRoute
  MarketplaceWearEgyptRoute: typeof MarketplaceWearEgyptRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia': {
      id: '/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof EncyclopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage-sites': {
      id: '/heritage-sites'
      path: '/heritage-sites'
      fullPath: '/heritage-sites'
      preLoaderRoute: typeof HeritageSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museums': {
      id: '/museums'
      path: '/museums'
      fullPath: '/museums'
      preLoaderRoute: typeof MuseumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concierge': {
      id: '/api/concierge'
      path: '/api/concierge'
      fullPath: '/api/concierge'
      preLoaderRoute: typeof ApiConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governorates/$id': {
      id: '/governorates/$id'
      path: '/governorates/$id'
      fullPath: '/governorates/$id'
      preLoaderRoute: typeof GovernoratesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/consent': {
      id: '/legal/consent'
      path: '/legal/consent'
      fullPath: '/legal/consent'
      preLoaderRoute: typeof LegalConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/review-checklist': {
      id: '/legal/review-checklist'
      path: '/legal/review-checklist'
      fullPath: '/legal/review-checklist'
      preLoaderRoute: typeof LegalReviewChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/egyptian-cotton': {
      id: '/marketplace/egyptian-cotton'
      path: '/marketplace/egyptian-cotton'
      fullPath: '/marketplace/egyptian-cotton'
      preLoaderRoute: typeof MarketplaceEgyptianCottonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/handmade-crafts': {
      id: '/marketplace/handmade-crafts'
      path: '/marketplace/handmade-crafts'
      fullPath: '/marketplace/handmade-crafts'
      preLoaderRoute: typeof MarketplaceHandmadeCraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/local-producers': {
      id: '/marketplace/local-producers'
      path: '/marketplace/local-producers'
      fullPath: '/marketplace/local-producers'
      preLoaderRoute: typeof MarketplaceLocalProducersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/wear-egypt': {
      id: '/marketplace/wear-egypt'
      path: '/marketplace/wear-egypt'
      fullPath: '/marketplace/wear-egypt'
      preLoaderRoute: typeof MarketplaceWearEgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EncyclopediaRoute: EncyclopediaRoute,
  EventsRoute: EventsRoute,
  HeritageSitesRoute: HeritageSitesRoute,
  MuseumsRoute: MuseumsRoute,
  ApiConciergeRoute: ApiConciergeRoute,
  GovernoratesIdRoute: GovernoratesIdRoute,
  LegalSlugRoute: LegalSlugRoute,
  LegalConsentRoute: LegalConsentRoute,
  LegalReviewChecklistRoute: LegalReviewChecklistRoute,
  MarketplaceEgyptianCottonRoute: MarketplaceEgyptianCottonRoute,
  MarketplaceHandmadeCraftsRoute: MarketplaceHandmadeCraftsRoute,
  MarketplaceLocalProducersRoute: MarketplaceLocalProducersRoute,
  MarketplaceWearEgyptRoute: MarketplaceWearEgyptRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
