/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as EgyptianHeritageWorldwideRouteImport } from './routes/egyptian-heritage-worldwide'
import { Route as EncyclopediaRouteImport } from './routes/encyclopedia'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HeritageSitesRouteImport } from './routes/heritage-sites'
import { Route as InvestmentOpportunitiesRouteImport } from './routes/investment-opportunities'
import { Route as MuseumsRouteImport } from './routes/museums'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ResearchProgramsRouteImport } from './routes/research-programs'
import { Route as TravelerStoriesRouteImport } from './routes/traveler-stories'
import { Route as AccountBookingsRouteImport } from './routes/account_.bookings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiConciergeRouteImport } from './routes/api/concierge'
import { Route as CountriesIdRouteImport } from './routes/countries_.$id'
import { Route as GovernoratesIdRouteImport } from './routes/governorates.$id'
import { Route as InvestmentOpportunitiesIdRouteImport } from './routes/investment-opportunities_.$id'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as LegalConsentRouteImport } from './routes/legal.consent'
import { Route as LegalReviewChecklistRouteImport } from './routes/legal.review-checklist'
import { Route as MarketplaceEgyptianCottonRouteImport } from './routes/marketplace.egyptian-cotton'
import { Route as MarketplaceHandmadeCraftsRouteImport } from './routes/marketplace.handmade-crafts'
import { Route as MarketplaceLocalProducersRouteImport } from './routes/marketplace.local-producers'
import { Route as MarketplaceWearEgyptRouteImport } from './routes/marketplace.wear-egypt'
import { Route as MyTripsIndexRouteImport } from './routes/my-trips.index'
import { Route as MyTripsNewRouteImport } from './routes/my-trips.new'
import { Route as OffersIdRouteImport } from './routes/offers_.$id'
import { Route as ProductsIdRouteImport } from './routes/products_.$id'
import { Route as PropertiesIdRouteImport } from './routes/properties_.$id'
import { Route as ProvidersIdRouteImport } from './routes/providers_.$id'
import { Route as TripsIdRouteImport } from './routes/trips.$id'
import { Route as AdminContentIndexRouteImport } from './routes/admin.content.index'
import { Route as AdminContentTableRouteImport } from './routes/admin.content.$table'
import { Route as AdminCrmInvestmentRouteImport } from './routes/admin.crm.investment'
import { Route as AdminCrmPropertiesRouteImport } from './routes/admin.crm.properties'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const EgyptianHeritageWorldwideRoute =
  EgyptianHeritageWorldwideRouteImport.update({
    id: '/egyptian-heritage-worldwide',
    path: '/egyptian-heritage-worldwide',
    getParentRoute: () => rootRouteImport,
  } as any)
const EncyclopediaRoute = EncyclopediaRouteImport.update({
  id: '/encyclopedia',
  path: '/encyclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageSitesRoute = HeritageSitesRouteImport.update({
  id: '/heritage-sites',
  path: '/heritage-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentOpportunitiesRoute = InvestmentOpportunitiesRouteImport.update({
  id: '/investment-opportunities',
  path: '/investment-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumsRoute = MuseumsRouteImport.update({
  id: '/museums',
  path: '/museums',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchProgramsRoute = ResearchProgramsRouteImport.update({
  id: '/research-programs',
  path: '/research-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelerStoriesRoute = TravelerStoriesRouteImport.update({
  id: '/traveler-stories',
  path: '/traveler-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/account_/bookings',
  path: '/account/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiConciergeRoute = ApiConciergeRouteImport.update({
  id: '/api/concierge',
  path: '/api/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIdRoute = CountriesIdRouteImport.update({
  id: '/countries_/$id',
  path: '/countries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernoratesIdRoute = GovernoratesIdRouteImport.update({
  id: '/governorates/$id',
  path: '/governorates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentOpportunitiesIdRoute =
  InvestmentOpportunitiesIdRouteImport.update({
    id: '/investment-opportunities_/$id',
    path: '/investment-opportunities/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConsentRoute = LegalConsentRouteImport.update({
  id: '/legal/consent',
  path: '/legal/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReviewChecklistRoute = LegalReviewChecklistRouteImport.update({
  id: '/legal/review-checklist',
  path: '/legal/review-checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceEgyptianCottonRoute =
  MarketplaceEgyptianCottonRouteImport.update({
    id: '/marketplace/egyptian-cotton',
    path: '/marketplace/egyptian-cotton',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceHandmadeCraftsRoute =
  MarketplaceHandmadeCraftsRouteImport.update({
    id: '/marketplace/handmade-crafts',
    path: '/marketplace/handmade-crafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceLocalProducersRoute =
  MarketplaceLocalProducersRouteImport.update({
    id: '/marketplace/local-producers',
    path: '/marketplace/local-producers',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceWearEgyptRoute = MarketplaceWearEgyptRouteImport.update({
  id: '/marketplace/wear-egypt',
  path: '/marketplace/wear-egypt',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsIndexRoute = MyTripsIndexRouteImport.update({
  id: '/my-trips/',
  path: '/my-trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsNewRoute = MyTripsNewRouteImport.update({
  id: '/my-trips/new',
  path: '/my-trips/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIdRoute = OffersIdRouteImport.update({
  id: '/offers_/$id',
  path: '/offers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties_/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers_/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTableRoute = AdminContentTableRouteImport.update({
  id: '/content/$table',
  path: '/content/$table',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmInvestmentRoute = AdminCrmInvestmentRouteImport.update({
  id: '/crm/investment',
  path: '/crm/investment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmPropertiesRoute = AdminCrmPropertiesRouteImport.update({
  id: '/crm/properties',
  path: '/crm/properties',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/egyptian-heritage-worldwide': typeof EgyptianHeritageWorldwideRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/events': typeof EventsRoute
  '/heritage-sites': typeof HeritageSitesRoute
  '/investment-opportunities': typeof InvestmentOpportunitiesRoute
  '/museums': typeof MuseumsRoute
  '/offers': typeof OffersRoute
  '/products': typeof ProductsRoute
  '/properties': typeof PropertiesRoute
  '/providers': typeof ProvidersRoute
  '/research-programs': typeof ResearchProgramsRoute
  '/traveler-stories': typeof TravelerStoriesRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/countries/$id': typeof CountriesIdRoute
  '/governorates/$id': typeof GovernoratesIdRoute
  '/investment-opportunities/$id': typeof InvestmentOpportunitiesIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/review-checklist': typeof LegalReviewChecklistRoute
  '/marketplace/egyptian-cotton': typeof MarketplaceEgyptianCottonRoute
  '/marketplace/handmade-crafts': typeof MarketplaceHandmadeCraftsRoute
  '/marketplace/local-producers': typeof MarketplaceLocalProducersRoute
  '/marketplace/wear-egypt': typeof MarketplaceWearEgyptRoute
  '/my-trips/new': typeof MyTripsNewRoute
  '/offers/$id': typeof OffersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/my-trips/': typeof MyTripsIndexRoute
  '/admin/content/$table': typeof AdminContentTableRoute
  '/admin/crm/investment': typeof AdminCrmInvestmentRoute
  '/admin/crm/properties': typeof AdminCrmPropertiesRoute
  '/admin/content/': typeof AdminContentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/egyptian-heritage-worldwide': typeof EgyptianHeritageWorldwideRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/events': typeof EventsRoute
  '/heritage-sites': typeof HeritageSitesRoute
  '/investment-opportunities': typeof InvestmentOpportunitiesRoute
  '/museums': typeof MuseumsRoute
  '/offers': typeof OffersRoute
  '/products': typeof ProductsRoute
  '/properties': typeof PropertiesRoute
  '/providers': typeof ProvidersRoute
  '/research-programs': typeof ResearchProgramsRoute
  '/traveler-stories': typeof TravelerStoriesRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/countries/$id': typeof CountriesIdRoute
  '/governorates/$id': typeof GovernoratesIdRoute
  '/investment-opportunities/$id': typeof InvestmentOpportunitiesIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/review-checklist': typeof LegalReviewChecklistRoute
  '/marketplace/egyptian-cotton': typeof MarketplaceEgyptianCottonRoute
  '/marketplace/handmade-crafts': typeof MarketplaceHandmadeCraftsRoute
  '/marketplace/local-producers': typeof MarketplaceLocalProducersRoute
  '/marketplace/wear-egypt': typeof MarketplaceWearEgyptRoute
  '/my-trips/new': typeof MyTripsNewRoute
  '/offers/$id': typeof OffersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin': typeof AdminIndexRoute
  '/legal': typeof LegalIndexRoute
  '/my-trips': typeof MyTripsIndexRoute
  '/admin/content/$table': typeof AdminContentTableRoute
  '/admin/crm/investment': typeof AdminCrmInvestmentRoute
  '/admin/crm/properties': typeof AdminCrmPropertiesRoute
  '/admin/content': typeof AdminContentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/egyptian-heritage-worldwide': typeof EgyptianHeritageWorldwideRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/events': typeof EventsRoute
  '/heritage-sites': typeof HeritageSitesRoute
  '/investment-opportunities': typeof InvestmentOpportunitiesRoute
  '/museums': typeof MuseumsRoute
  '/offers': typeof OffersRoute
  '/products': typeof ProductsRoute
  '/properties': typeof PropertiesRoute
  '/providers': typeof ProvidersRoute
  '/research-programs': typeof ResearchProgramsRoute
  '/traveler-stories': typeof TravelerStoriesRoute
  '/account_/bookings': typeof AccountBookingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/countries_/$id': typeof CountriesIdRoute
  '/governorates/$id': typeof GovernoratesIdRoute
  '/investment-opportunities_/$id': typeof InvestmentOpportunitiesIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/review-checklist': typeof LegalReviewChecklistRoute
  '/marketplace/egyptian-cotton': typeof MarketplaceEgyptianCottonRoute
  '/marketplace/handmade-crafts': typeof MarketplaceHandmadeCraftsRoute
  '/marketplace/local-producers': typeof MarketplaceLocalProducersRoute
  '/marketplace/wear-egypt': typeof MarketplaceWearEgyptRoute
  '/my-trips/new': typeof MyTripsNewRoute
  '/offers_/$id': typeof OffersIdRoute
  '/products_/$id': typeof ProductsIdRoute
  '/properties_/$id': typeof PropertiesIdRoute
  '/providers_/$id': typeof ProvidersIdRoute
  '/trips/$id': typeof TripsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/my-trips/': typeof MyTripsIndexRoute
  '/admin/content/$table': typeof AdminContentTableRoute
  '/admin/crm/investment': typeof AdminCrmInvestmentRoute
  '/admin/crm/properties': typeof AdminCrmPropertiesRoute
  '/admin/content/': typeof AdminContentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/countries'
    | '/egyptian-heritage-worldwide'
    | '/encyclopedia'
    | '/events'
    | '/heritage-sites'
    | '/investment-opportunities'
    | '/museums'
    | '/offers'
    | '/products'
    | '/properties'
    | '/providers'
    | '/research-programs'
    | '/traveler-stories'
    | '/account/bookings'
    | '/admin/bookings'
    | '/admin/integrations'
    | '/admin/maintenance'
    | '/admin/users'
    | '/api/concierge'
    | '/countries/$id'
    | '/governorates/$id'
    | '/investment-opportunities/$id'
    | '/legal/$slug'
    | '/legal/consent'
    | '/legal/review-checklist'
    | '/marketplace/egyptian-cotton'
    | '/marketplace/handmade-crafts'
    | '/marketplace/local-producers'
    | '/marketplace/wear-egypt'
    | '/my-trips/new'
    | '/offers/$id'
    | '/products/$id'
    | '/properties/$id'
    | '/providers/$id'
    | '/trips/$id'
    | '/admin/'
    | '/legal/'
    | '/my-trips/'
    | '/admin/content/$table'
    | '/admin/crm/investment'
    | '/admin/crm/properties'
    | '/admin/content/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/contact'
    | '/countries'
    | '/egyptian-heritage-worldwide'
    | '/encyclopedia'
    | '/events'
    | '/heritage-sites'
    | '/investment-opportunities'
    | '/museums'
    | '/offers'
    | '/products'
    | '/properties'
    | '/providers'
    | '/research-programs'
    | '/traveler-stories'
    | '/account/bookings'
    | '/admin/bookings'
    | '/admin/integrations'
    | '/admin/maintenance'
    | '/admin/users'
    | '/api/concierge'
    | '/countries/$id'
    | '/governorates/$id'
    | '/investment-opportunities/$id'
    | '/legal/$slug'
    | '/legal/consent'
    | '/legal/review-checklist'
    | '/marketplace/egyptian-cotton'
    | '/marketplace/handmade-crafts'
    | '/marketplace/local-producers'
    | '/marketplace/wear-egypt'
    | '/my-trips/new'
    | '/offers/$id'
    | '/products/$id'
    | '/properties/$id'
    | '/providers/$id'
    | '/trips/$id'
    | '/admin'
    | '/legal'
    | '/my-trips'
    | '/admin/content/$table'
    | '/admin/crm/investment'
    | '/admin/crm/properties'
    | '/admin/content'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/countries'
    | '/egyptian-heritage-worldwide'
    | '/encyclopedia'
    | '/events'
    | '/heritage-sites'
    | '/investment-opportunities'
    | '/museums'
    | '/offers'
    | '/products'
    | '/properties'
    | '/providers'
    | '/research-programs'
    | '/traveler-stories'
    | '/account_/bookings'
    | '/admin/bookings'
    | '/admin/integrations'
    | '/admin/maintenance'
    | '/admin/users'
    | '/api/concierge'
    | '/countries_/$id'
    | '/governorates/$id'
    | '/investment-opportunities_/$id'
    | '/legal/$slug'
    | '/legal/consent'
    | '/legal/review-checklist'
    | '/marketplace/egyptian-cotton'
    | '/marketplace/handmade-crafts'
    | '/marketplace/local-producers'
    | '/marketplace/wear-egypt'
    | '/my-trips/new'
    | '/offers_/$id'
    | '/products_/$id'
    | '/properties_/$id'
    | '/providers_/$id'
    | '/trips/$id'
    | '/admin/'
    | '/legal/'
    | '/my-trips/'
    | '/admin/content/$table'
    | '/admin/crm/investment'
    | '/admin/crm/properties'
    | '/admin/content/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRoute
  EgyptianHeritageWorldwideRoute: typeof EgyptianHeritageWorldwideRoute
  EncyclopediaRoute: typeof EncyclopediaRoute
  EventsRoute: typeof EventsRoute
  HeritageSitesRoute: typeof HeritageSitesRoute
  InvestmentOpportunitiesRoute: typeof InvestmentOpportunitiesRoute
  MuseumsRoute: typeof MuseumsRoute
  OffersRoute: typeof OffersRoute
  ProductsRoute: typeof ProductsRoute
  PropertiesRoute: typeof PropertiesRoute
  ProvidersRoute: typeof ProvidersRoute
  ResearchProgramsRoute: typeof ResearchProgramsRoute
  TravelerStoriesRoute: typeof TravelerStoriesRoute
  AccountBookingsRoute: typeof AccountBookingsRoute
  ApiConciergeRoute: typeof ApiConciergeRoute
  CountriesIdRoute: typeof CountriesIdRoute
  GovernoratesIdRoute: typeof GovernoratesIdRoute
  InvestmentOpportunitiesIdRoute: typeof InvestmentOpportunitiesIdRoute
  LegalSlugRoute: typeof LegalSlugRoute
  LegalConsentRoute: typeof LegalConsentRoute
  LegalReviewChecklistRoute: typeof LegalReviewChecklistRoute
  MarketplaceEgyptianCottonRoute: typeof MarketplaceEgyptianCottonRoute
  MarketplaceHandmadeCraftsRoute: typeof MarketplaceHandmadeCraftsRoute
  MarketplaceLocalProducersRoute: typeof MarketplaceLocalProducersRoute
  MarketplaceWearEgyptRoute: typeof MarketplaceWearEgyptRoute
  MyTripsNewRoute: typeof MyTripsNewRoute
  OffersIdRoute: typeof OffersIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  TripsIdRoute: typeof TripsIdRoute
  LegalIndexRoute: typeof LegalIndexRoute
  MyTripsIndexRoute: typeof MyTripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egyptian-heritage-worldwide': {
      id: '/egyptian-heritage-worldwide'
      path: '/egyptian-heritage-worldwide'
      fullPath: '/egyptian-heritage-worldwide'
      preLoaderRoute: typeof EgyptianHeritageWorldwideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia': {
      id: '/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof EncyclopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage-sites': {
      id: '/heritage-sites'
      path: '/heritage-sites'
      fullPath: '/heritage-sites'
      preLoaderRoute: typeof HeritageSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-opportunities': {
      id: '/investment-opportunities'
      path: '/investment-opportunities'
      fullPath: '/investment-opportunities'
      preLoaderRoute: typeof InvestmentOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museums': {
      id: '/museums'
      path: '/museums'
      fullPath: '/museums'
      preLoaderRoute: typeof MuseumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-programs': {
      id: '/research-programs'
      path: '/research-programs'
      fullPath: '/research-programs'
      preLoaderRoute: typeof ResearchProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traveler-stories': {
      id: '/traveler-stories'
      path: '/traveler-stories'
      fullPath: '/traveler-stories'
      preLoaderRoute: typeof TravelerStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/bookings': {
      id: '/account_/bookings'
      path: '/account/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/concierge': {
      id: '/api/concierge'
      path: '/api/concierge'
      fullPath: '/api/concierge'
      preLoaderRoute: typeof ApiConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries_/$id': {
      id: '/countries_/$id'
      path: '/countries/$id'
      fullPath: '/countries/$id'
      preLoaderRoute: typeof CountriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governorates/$id': {
      id: '/governorates/$id'
      path: '/governorates/$id'
      fullPath: '/governorates/$id'
      preLoaderRoute: typeof GovernoratesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-opportunities_/$id': {
      id: '/investment-opportunities_/$id'
      path: '/investment-opportunities/$id'
      fullPath: '/investment-opportunities/$id'
      preLoaderRoute: typeof InvestmentOpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/consent': {
      id: '/legal/consent'
      path: '/legal/consent'
      fullPath: '/legal/consent'
      preLoaderRoute: typeof LegalConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/review-checklist': {
      id: '/legal/review-checklist'
      path: '/legal/review-checklist'
      fullPath: '/legal/review-checklist'
      preLoaderRoute: typeof LegalReviewChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/egyptian-cotton': {
      id: '/marketplace/egyptian-cotton'
      path: '/marketplace/egyptian-cotton'
      fullPath: '/marketplace/egyptian-cotton'
      preLoaderRoute: typeof MarketplaceEgyptianCottonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/handmade-crafts': {
      id: '/marketplace/handmade-crafts'
      path: '/marketplace/handmade-crafts'
      fullPath: '/marketplace/handmade-crafts'
      preLoaderRoute: typeof MarketplaceHandmadeCraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/local-producers': {
      id: '/marketplace/local-producers'
      path: '/marketplace/local-producers'
      fullPath: '/marketplace/local-producers'
      preLoaderRoute: typeof MarketplaceLocalProducersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/wear-egypt': {
      id: '/marketplace/wear-egypt'
      path: '/marketplace/wear-egypt'
      fullPath: '/marketplace/wear-egypt'
      preLoaderRoute: typeof MarketplaceWearEgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips/': {
      id: '/my-trips/'
      path: '/my-trips'
      fullPath: '/my-trips/'
      preLoaderRoute: typeof MyTripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips/new': {
      id: '/my-trips/new'
      path: '/my-trips/new'
      fullPath: '/my-trips/new'
      preLoaderRoute: typeof MyTripsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers_/$id': {
      id: '/offers_/$id'
      path: '/offers/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof OffersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$id': {
      id: '/products_/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties_/$id': {
      id: '/properties_/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers_/$id': {
      id: '/providers_/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/$table': {
      id: '/admin/content/$table'
      path: '/content/$table'
      fullPath: '/admin/content/$table'
      preLoaderRoute: typeof AdminContentTableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/investment': {
      id: '/admin/crm/investment'
      path: '/crm/investment'
      fullPath: '/admin/crm/investment'
      preLoaderRoute: typeof AdminCrmInvestmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/properties': {
      id: '/admin/crm/properties'
      path: '/crm/properties'
      fullPath: '/admin/crm/properties'
      preLoaderRoute: typeof AdminCrmPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContentTableRoute: typeof AdminContentTableRoute
  AdminCrmInvestmentRoute: typeof AdminCrmInvestmentRoute
  AdminCrmPropertiesRoute: typeof AdminCrmPropertiesRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContentTableRoute: AdminContentTableRoute,
  AdminCrmInvestmentRoute: AdminCrmInvestmentRoute,
  AdminCrmPropertiesRoute: AdminCrmPropertiesRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRoute,
  EgyptianHeritageWorldwideRoute: EgyptianHeritageWorldwideRoute,
  EncyclopediaRoute: EncyclopediaRoute,
  EventsRoute: EventsRoute,
  HeritageSitesRoute: HeritageSitesRoute,
  InvestmentOpportunitiesRoute: InvestmentOpportunitiesRoute,
  MuseumsRoute: MuseumsRoute,
  OffersRoute: OffersRoute,
  ProductsRoute: ProductsRoute,
  PropertiesRoute: PropertiesRoute,
  ProvidersRoute: ProvidersRoute,
  ResearchProgramsRoute: ResearchProgramsRoute,
  TravelerStoriesRoute: TravelerStoriesRoute,
  AccountBookingsRoute: AccountBookingsRoute,
  ApiConciergeRoute: ApiConciergeRoute,
  CountriesIdRoute: CountriesIdRoute,
  GovernoratesIdRoute: GovernoratesIdRoute,
  InvestmentOpportunitiesIdRoute: InvestmentOpportunitiesIdRoute,
  LegalSlugRoute: LegalSlugRoute,
  LegalConsentRoute: LegalConsentRoute,
  LegalReviewChecklistRoute: LegalReviewChecklistRoute,
  MarketplaceEgyptianCottonRoute: MarketplaceEgyptianCottonRoute,
  MarketplaceHandmadeCraftsRoute: MarketplaceHandmadeCraftsRoute,
  MarketplaceLocalProducersRoute: MarketplaceLocalProducersRoute,
  MarketplaceWearEgyptRoute: MarketplaceWearEgyptRoute,
  MyTripsNewRoute: MyTripsNewRoute,
  OffersIdRoute: OffersIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  TripsIdRoute: TripsIdRoute,
  LegalIndexRoute: LegalIndexRoute,
  MyTripsIndexRoute: MyTripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
